import FWCore.ParameterSet.Config as cms

simpleNtupleEoverPsingleParticle = cms.EDAnalyzer(
    "SimpleNtupleEoverPsingleParticle",
    MCPileupTag         = cms.InputTag("addPileupInfo"),
    PVTag               = cms.InputTag("offlinePrimaryVerticesWithBS"),
    reducedrecHitCollection_EB = cms.InputTag("reducedEcalRecHitsEB"),
    reducedrecHitCollection_EE = cms.InputTag("reducedEcalRecHitsEE"),
    reducedrecHitCollection_ES = cms.InputTag("reducedEcalRecHitsES"),
    recHitCollection_EE       = cms.InputTag("ecalRecHit","EcalRecHitsEE"),
    recHitCollection_EB       = cms.InputTag("ecalRecHit","EcalRecHitsEB"),
    recHitCollection_ES       = cms.InputTag("ecalPreshowerRecHit","EcalRecHitsES"),
    SRFlagCollection_EB = cms.InputTag("ecalDigis"),
    SRFlagCollection_EE = cms.InputTag("ecalDigis"),
    digiCollection_EB   = cms.InputTag("ecalDigis","ebDigis"),
    digiCollection_EE   = cms.InputTag("ecalDigis","eeDigis"),
    EleTag              = cms.InputTag("gedGsfElectrons"),
    PhoTag              = cms.InputTag("gedPhotons"),
    PFMetTag            = cms.InputTag("pfMet"),
    theBeamSpotTag      = cms.InputTag("offlineBeamSpot"),
    MCtruthTag          = cms.InputTag("genParticles"),
#    rhoTag              = cms.InputTag("kt6PFJets","rho"),
    rhoTag              = cms.InputTag("kt6PFJetsForRhoCorrection","rho"),
    conversionsInputTag = cms.InputTag("allConversions"),
    jsonFileName        = cms.string("dummy.txt"),
    dataRun             = cms.string("noCorrection"),
    jsonFlag            = cms.untracked.bool(False),
    verbosity           = cms.untracked.bool(True),
    particleIsEle       = cms.untracked.bool(True),
    doWZSelection       = cms.untracked.bool(False),
    applyCorrections    = cms.untracked.bool(False),
    saveMCPU            = cms.untracked.bool(False),
    saveMCInfo          = cms.untracked.bool(False),
    dataFlag            = cms.untracked.bool(True),
    saveRecHitMatrix    = cms.untracked.bool(False),
    saveFbrem           = cms.untracked.bool(False) # set False if running on AOD
    )
